# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(455, 157)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 351, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_parameter_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_parameter_name.setObjectName("label_parameter_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_parameter_name)
        self.combo_parameter_name = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_parameter_name.setObjectName("combo_parameter_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_parameter_name)
        self.label_lower_limit = QtWidgets.QLabel(self.layoutWidget)
        self.label_lower_limit.setObjectName("label_lower_limit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_lower_limit)
        self.spin_box_lower_limit = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spin_box_lower_limit.setObjectName("spin_box_lower_limit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_box_lower_limit)
        self.label_upper_limit = QtWidgets.QLabel(self.layoutWidget)
        self.label_upper_limit.setObjectName("label_upper_limit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_upper_limit)
        self.spin_box_upper_limit = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spin_box_upper_limit.setObjectName("spin_box_upper_limit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_box_upper_limit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.slider_lower_limit = QtWidgets.QSlider(self.layoutWidget)
        self.slider_lower_limit.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lower_limit.setObjectName("slider_lower_limit")
        self.verticalLayout_2.addWidget(self.slider_lower_limit)
        self.slider_upper_limit = QtWidgets.QSlider(self.layoutWidget)
        self.slider_upper_limit.setOrientation(QtCore.Qt.Horizontal)
        self.slider_upper_limit.setObjectName("slider_upper_limit")
        self.verticalLayout_2.addWidget(self.slider_upper_limit)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(372, 12, 75, 52))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit a filter"))
        self.label_parameter_name.setText(_translate("Dialog", "Parameter"))
        self.label_lower_limit.setText(_translate("Dialog", "Lower Limit"))
        self.label_upper_limit.setText(_translate("Dialog", "Upper Limit"))
